version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.0
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: npm install
      - run:
          name: Ejecutar tests
          command: npm test

  deploy:
    docker:
      - image: cimg/node:20.0
    steps:
      - checkout
      - run:
          name: Compilar aplicación
          command: npm run build
      - run:
          name: Desplegar aplicación
          command: echo "🚀 Desplegando aplicación (ejemplo)"

workflows:
  version: 2
  ci_cd_pipeline:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
